version: "3.1"

services:

  nginx:
    image: docker.io/nginx:latest
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8876:80
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.shatynskyj.entrypoints=websecure"
      - "traefik.http.routers.shatynskyj.rule=Host(`shatynskyj.in.ua`)"
      - "traefik.http.routers.shatynskyj.tls=true"
      - "traefik.http.routers.shatynskyj.tls.certresolver=leresolver"
    networks:
      - traefik-public
    depends_on:
      - app
    container_name: shatynskyj_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    user: 1000:1000
    container_name: shatynskyj_app
    restart: unless-stopped

networks:
  traefik-public:
    external: true